"""zencontrol TPI Advanced protocol library."""
from .client import TpiClient
from .commands import (
    ColourState,
    ColourTempLimits,
    ControllerInfo,
    DeviceColourFeatures,
    GroupInfo,
    ProfileInfo,
    ProfileInformation,
    SceneInfo,
    ZenCommands,
    parse_colour_payload,
)
from .const import (
    ARC_LEVEL_MAX,
    ARC_LEVEL_MIN,
    ARC_LEVEL_MIXED,
    ARC_LEVEL_OFF,
    DALI_BROADCAST,
    DALI_GROUP_OFFSET,
    DALI_MAX_GROUP,
    DALI_MAX_SHORT_ADDRESS,
    PROFILE_SCHEDULE,
    TPI_PORT,
    ColourType,
    Command,
    DaliCgTypeMask,
    DaliStatusMask,
    ErrorCode,
    EventType,
    ResponseType,
    TpiEventMode,
    group_to_address,
    address_to_group,
    is_group_address,
)
from .event_listener import EventListener
from .protocol import TpiEvent, parse_event

__all__ = [
    "TpiClient",
    "ZenCommands",
    "EventListener",
    "TpiEvent",
    "parse_event",
    "parse_colour_payload",
    # Data classes
    "ColourState",
    "ColourTempLimits",
    "ControllerInfo",
    "DeviceColourFeatures",
    "GroupInfo",
    "ProfileInfo",
    "ProfileInformation",
    "SceneInfo",
    # Constants / enums
    "ARC_LEVEL_MAX",
    "ARC_LEVEL_MIN",
    "ARC_LEVEL_MIXED",
    "ARC_LEVEL_OFF",
    "DALI_BROADCAST",
    "DALI_GROUP_OFFSET",
    "DALI_MAX_GROUP",
    "DALI_MAX_SHORT_ADDRESS",
    "PROFILE_SCHEDULE",
    "TPI_PORT",
    "ColourType",
    "Command",
    "DaliCgTypeMask",
    "DaliStatusMask",
    "ErrorCode",
    "EventType",
    "ResponseType",
    "TpiEventMode",
    "group_to_address",
    "address_to_group",
    "is_group_address",
]
